// Generated by MARIGOLD-BATCH-APP (5-field outreach batch).
import type { MarigoldConfig } from "./config";

export const BUSINESS: MarigoldConfig = {
  "businessName": "Fortuna Coffee Bar",
  "location": "",
  "palette": "marigold-green",
  "fontSet": "fraunces-dmsans",
  "heroImage": "/hero.jpg",
  "aboutQuote": "We opened Fortuna Coffee Bar to be the kind of place we missed — somewhere warm, where the bread is real, the coffee is strong and nobody is in a rush.",
  "aboutAttribution": "— The owners",
  "phone": "0131 467 0179",
  "email": "hello@fortunaqueenst.co.uk",
  "address": [
    "41 Frederick street Edinburgh"
  ]
};
